---
- name: This play book install packages
  hosts: webserver
  become: true
  tasks:
    - name: installing package
      yum:
        name: ['git', 'make', 'gcc', 'mysql', 'which', 'docker',]
        state: installed

