---
- name: This play book install httpd packages
  hosts: webserver
  become: true
  tasks:
    - name: installing httpd package
      yum:
        name: httpd
        state: installed
    - name: httpd service starting 
      service: 
        name: httpd
        state: started
    - name: copy file 
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html 

