---
- name: my test playbook
  hosts: webserver
  become: true
  tasks:
    - name: installing packages httpd
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"

    - name: httpd services starting
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
        #ignore_errors: yes

    - name: installing packages apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: apache2 services starting
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

