---
# tasks file for setup-web-role
- name: installing packages httpd
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  notify: httpd services starting

- name: installing packages apache2
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: apache2 services starting

- name: copy file from server
  copy:
   src: /home/ansadmin/index.html
   dest: /var/www/html/
   mode: 0777



